name: Run

on:
  push:
    branches: [ test, main ]
  pull_request:
    branches: [ test, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver xvfb

    - name: Initialize database
      env:
        DATABASE_URL: sqlite:////home/runner/work/simple-blog-platform/simple-blog-platform/blog.db
      run: |
        PYTHONPATH=. python -c "from blogapp import app, db; from blogapp.models import User, UserRole; app.app_context().push(); db.create_all(); u = User(name='Ngọc Sơn', username='ngocson', password='e10adc3949ba59abbe56e057f20f883e', email='ngocson@example.com', user_role=UserRole.USER); db.session.add(u); db.session.commit()"

    - name: Run tests
      env:
        DATABASE_URL: sqlite:////home/runner/work/simple-blog-platform/simple-blog-platform/blog.db
        PYTHONPATH: .
        CHROME_DRIVER_PATH: /usr/bin/chromedriver
      run: |
        python blogapp/index.py &
        sleep 5
        xvfb-run -a pytest blogapp
